### ISSUE TITLE
Add Issue And PR Tempaltes

### ISSUE THREAD

**Issue by muthuannamalai12** [harikanani/AutomateInstaPyBot#14]
Would like to add issue and pr templates to these project that will basically explain the type of issue and its description and also the type of pr the set of checklist that it obeys and its description

Kindly assign this to me as a part of Cross-Woc. I would love to do it

**Comment by harikanani** [comment]
@muthuannamalai12  can you share the screenshot of what you would like to add?

**Comment by muthuannamalai12** [comment]
Issue Template : 
![Issue](https://user-images.githubusercontent.com/64524822/107934009-82d1b300-6fa5-11eb-9a78-abadc5ec261b.jpeg)

PR Template :
![Screenshot (41)](https://user-images.githubusercontent.com/64524822/107934371-fb387400-6fa5-11eb-8386-d03ff5cb9b79.png)
![Screenshot (42)](https://user-images.githubusercontent.com/64524822/107934375-fd023780-6fa5-11eb-8b5a-3a1402265989.png)

**Comment by harikanani** [comment]
Hey! @muthuannamalai12 don't be greedy, just complete onw issue first for what you've requested I've assigned that task to you. First complete that

**Comment by muthuannamalai12** [comment]
> Hey! @muthuannamalai12 don't be greedy, just complete onw issue first for what you've requested I've assigned that task to you. First complete that

I have opened two issues and I have completed both. My two PR no are #9 and #12 . I have completed the issues I have been assigned for and I am asking a new issue.

**Comment by muthuannamalai12** [comment]
#9 - Code of Conduct, Contributing, Contribution file
#12 - Intergrate Welcome Bot
Both my PR are merged too

**Comment by abhigoyani** [comment]
@muthuannamalai12 you can start working on it.
Happy hacking.
