### ISSUE TITLE
Add requirements.txt file 

### ISSUE THREAD

**Issue by Akash20x** [harikanani/AutomateInstaPyBot#19]
## Reason or Problem 

Want to add requirements.txt file in your repo so that user can run that script and install all requirements in their system for proper working of project.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by harikanani** [comment]
@Akash20x , start working on the issue

**Comment by Akash20x** [comment]
Please merge my pull request

**Comment by Akash20x** [comment]
Please check this pull request
