### ISSUE TITLE
Unfollow Functionality is not working  I'm Opening it for Open Source contribution

### ISSUE THREAD

**Issue by harikanani** [harikanani/AutomateInstaPyBot#2]
# Bug Found for Unfollow Functionality
*   In my Code Unfollow Functionality is not Working as instagram version changes and made some updates on instagram.
so I'm Opening this Issue for contributes to contribute on this issue and solve this.
* Start Working on this Repository and Fix the Issue.
* Once fix the issue then send pull request.

**Comment by gracyashhh** [comment]
I can help you with that

**Comment by harikanani** [comment]
I've Assigned this issue to you and closing the issue
