### ISSUE TITLE
Automatically Like All the Post

### ISSUE THREAD

**Issue by harikanani** [harikanani/AutomateInstaPyBot#6]
* ##  Like Automation
* Open the Instagram and Start Liking All the Post and Scroll down and repeat the steps.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by harikanani** [comment]
hello,  @Akash20x I would like to assign this task to you but you have to know about PR.

create a new branch named username/autoliker and then start working on that branch and then ask for PR.

**Comment by Akash20x** [comment]
OK, I will do it as you mentioned

**Comment by Akash20x** [comment]
OK, Got it

**Comment by harikanani** [comment]
Hello 👋, @Akash20x jiin Discord channel for further discussion and doubt solving 👇
https://discord.gg/Mw4YFRJNxk

**Comment by Akash20x** [comment]
Just an update :

I will started working on it and send pull request by today.

**Comment by Akash20x** [comment]
Please review the pull request

**Comment by Akash20x** [comment]
Please merge the pull request

**Comment by harikanani** [comment]
Hey! @Akash20x , I think you have made a PR in your own Repository, you've to make a PR on my Repo. if you don't know how to make a PR then refer to the CONTRIBUTING.md file.

**Comment by Akash20x** [comment]
OK let me check and do it

**Comment by Akash20x** [comment]
Done Now
