### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [harikanani/AutomateInstaPyBot#7]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me as a part of Cross Woc

**Comment by harikanani** [comment]
hey @muthuannamalai12  , 
It's a great idea to have this kinda stuffs. start working on a project and make sure about PR.

kindly create a new branch with a username/feature_name and start working on that branch.

**Comment by harikanani** [comment]
Thank you for your contribution @muthuannamalai12 
Happing Hacking 😊.
