### ISSUE TITLE
Create Code of Conduct.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [harikanani/AutomateInstaPyBot#8]
Hello there,
I would like to add CODE_OF_CONDUCT.md for this Project. Kindly assign me this issue.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross Woc. Kindly assign it to me.

**Comment by harikanani** [comment]
hello 👋, @muthuannamalai12 , I would like to assign this task to you.

kindly also add CONTRIBUTING.md and CONTRIBUTION.md files if you can.

May I know can you do this or not?

**Comment by muthuannamalai12** [comment]
> hello , @muthuannamalai12 , I would like to assign this task to you.
> 
> kindly also add CONTRIBUTING.md and CONTRIBUTION.md files if you can.
> 
> May I know can you do this or not?

Yes, I can do it. I have a doubt CONTRIBUTION.md is similar to the CONTRIBUTORS.md file

**Comment by harikanani** [comment]
no in CONTRIBUTION.md file you will write about how to contribute to this project how to run the code in the local system and how to make PR.

and for CONTRIBUTORS.md file you'll write all the CONTRIBUTORS name with their GitHub User Profile.

**Comment by muthuannamalai12** [comment]
> no in CONTRIBUTION.md file you will write about how to contribute to this project how to run the code in the local system and how to make PR.
> 
> and for CONTRIBUTORS.md file you'll write all the CONTRIBUTORS name with their GitHub User Profile.

Yes I have got your point and I will add Contribution. md and Contributors.md in your project

**Comment by muthuannamalai12** [comment]
Thank you explaining

**Comment by harikanani** [comment]
hope you know about the branching rule for this project.

if you don't know then refer to this 👇

branch name would be: username/feature_name

**Comment by muthuannamalai12** [comment]
Can I add all 3 files in one PR or you want me to create a separate PR for each one??

**Comment by harikanani** [comment]
No, in one PR.

**Comment by muthuannamalai12** [comment]
> No, in one PR.

Ok. Thank you

**Comment by harikanani** [comment]
@muthuannamalai12 I would like you to join our discord server for further discussion and doubts

you can refer the readme.md file or join through here 👇 
https://discord.gg/Mw4YFRJNxk
